config/routes.rb
p 'routes is initializing'

Rails.application.routes.draw do
  root 'home#index'
  match 'console' => 'home#console', via: :all

  # SessionsController
  match '/login(?redirect_to=:redirect_page)', to: 'sessions#new', via: :get, as: :signin
  match '/login', to: 'sessions#create', via: :post
  match '/signout(?redirect_to=:redirect_page)', to: 'sessions#destroy', via: :delete, as: :signout
  get '/users/find'


  # UsersController
  match '/register(?redirect_to=:redirect_page)', to: 'users#new', via: :get, as: :signup
  match '/register', to: 'users#create', via: :post
  match '/users', to: 'users#index', via: :get
  match '/settings', to: 'users#edit_current_user', via: :get, as: :current_user_settings # only singed in
  match '/settings', to: 'users#update_current_user', via: :patch # only singed in
  resources :users, only: [:edit, :show] # only admin


  resources :books
  match 'books/new' => 'books#create', via: :post


  resources :authors
  match 'authors/new' => 'authors#create', via: :post


  resources :publishing_houses
  match 'publishing_houses/new' => 'publishing_houses#create', via: :post
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :abstract_book
  has_many :authors, through: :abstract_book
  belongs_to :publishing_house

  validates :name, length: {minimum: 2, maximum: 50}
  validates :language, length: {minimum: 2, maximum: 5}
  validates :poster, presence: true
  validates :published_at, presence: true
  validate :check_type

  mount_uploader :poster, ImageUploader
  mount_uploader :background_image, ImageUploader


  def background_stable_image
    background_image.nil? ? poster : background_image
  end

  private
    def check_type
      unless type == Ebook::name or type == Audiobook::name
        errors[:type] << 'Type must be "Ebook" or "Audiobook"'
      end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :fill_publishing_houses, only: :new

  def index
    books = Book
                .where(type: 'Ebook')
                .limit(6)
                .union(Book.where(type: 'Audiobook').limit(7))
                .order(:type)
                .includes(abstract_book: :book_series)
                .includes(abstract_book: :authors)
    # p books.map{|b| b.abstract_book_id}
    @ebooks = books.find_all{|b| b.class == Ebook}
    @audiobooks = books.find_all{|b| b.class == Audiobook}
  end

  def new
    @book = Book.new
    @abstract_book = AbstractBook.new
  end

  def create
    @book = Book.new params_book

    if (sbid = params[:same_book_id]).present?
      b = Book.eager_load(:abstract_book).find_by_id(sbid)
      if b.nil?
        flash.now[:notice] = "Book with id = #{sbid} not found"
        fill_publishing_houses
        @abstract_book = AbstractBook.new
        return render new_book_path
      end
      @abstract_book = @book.abstract_book = b.abstract_book
      # @book.abstract_book_id = b.abstract_book_id
    else
      @abstract_book = AbstractBook.new(params.require(:abstract_book).permit(:original_name, :published_at))
      author_ids = params[:author_ids].gsub(' ', '').split(',')
      if @abstract_book.invalid? or author_ids.empty?
        flash.now[:abstract_book_errors] = @abstract_book.errors.messages if @abstract_book.invalid?
        flash.now[:author_ids_errors] = 'Author ids cannot be empty' if author_ids.empty?
        fill_publishing_houses
        return render new_book_path
      end
      ActiveRecord::Base.transaction do
        i = 0
        author_ids.each do |id|
          AbstractBookAuthor.create!(author_id: id, abstract_book: @abstract_book, position: i)
          i += 1
        end
      end
      @book.abstract_book = @abstract_book
    end

    if @book.save
      redirect_to book_path(@book), notice: 'Books is successfully created'
    else
      flash.now[:errors] = @book.errors.messages
      fill_publishing_houses
      render new_book_path
    end
  end

  def show
    @book = Book.find params[:id]
  end

  def destroy
    book = Book.eager_load(:abstract_book).where(id: params[:id])[0]
    notice = nil
    ActiveRecord::Base.transaction do
      book.destroy
      if Book.where(abstract_book: book.abstract_book).empty?
        book.abstract_book.destroy
        notice = "The book '#{book.name}' is completely deleted"
      else
        notice = "The book '#{book.name}' is deleted"
      end
    end
    redirect_to books_path, notice: notice
  end

  private
    def params_book
      if params[:book]
        type = :book
      elsif params[:ebook]
        type = :ebook
      elsif params[:audiobook]
        type = :audiobook
      else
        return
      end
      params.require(type).permit :name, :description, :abstract_book_id, :language,
                                   :background_image, :poster, :remote_poster_url,
                                   :remote_background_image_url, :published_at,
                                   :author_ids, :publishing_house_id, :type
    end

    def params_abstract_book

    end

    def fill_publishing_houses
      @publishing_houses = PublishingHouse.all.reverse_order!
    end
end

app/views/books/index.html.erb
<%=provide :common_lower_title, 'книга'%>
<%=link_to 'Add new book', new_book_path%>
<br>
<%=@ebooks.size%>
<%=@audiobooks.size%>
<%=render 'shared/books'%>

app/views/books/index.js.erb
console.log('<%=request.path%>');
var page = <%=params[:page] || 1%>;
var path = '/books';
if (page !== 1) path += '?page=' + page;

if (location.href !== location.origin + path) {
    history.pushState({scrollTopBody: document.body.scrollTop}, `Book ${page}`, path);
    document.title = 'Book ' + page;
}
$("#part-of-books").text("data from page " + page);
//console.log(path);

app/views/books/new.html.erb
<%=provide :common_lower_title, 'добавление'%>
<%= stylesheet_link_tag "/assets/stylesheets/edit-book.css" %>

<div class="main-column">
  <h1>Добавление</h1>

  <%if !flash[:errors].blank?%>
      <%=flash[:errors].inspect%>
  <%end%>

  <script type="text/javascript" charset="utf-8">
  angular.module('main', []).controller('addBookCtrl', function ($scope, $sce) {
    var converter = new showdown.Converter();
    $scope.plainText = '<%=j @book.description%>'
    $scope.convertToHtml = function() {
        $scope.width = 500;
        $scope.height = 300;
        var html = converter.makeHtml($scope.plainText);
        $scope.markdownText = $sce.trustAsHtml(html);
    };
  });
  </script>
  <br>

  <%#=params[:book].inspect%>

  <div ng-controller="addBookCtrl">
    <%=form_for @book, url: new_book_path  do |f|%>
        <%=f.text_field :name, placeholder: 'Book name'%>
        <div>
          <%=f.text_area :description, placeholder: 'Description',
                              style: 'min-width: 500px; min-height: 200px;width: {{width}}; height: {{height}};',
                              'ng-model' => 'plainText', 'ng-change' => 'convertToHtml()', 'ng-resize' => 'sad'%>
          <div id="markdorn_description" ng-bind-html="markdownText"
               style="display: inline-block; min-width: 400px; min-height: 200px; position: absolute; outline: 1px solid;"></div>
        </div>
        <div>
          <%=f.radio_button :type, 'Ebook' %>
          <%= f.label :type_ebook, 'Ebook' %>
          <br>
          <%= f.radio_button :type, 'Audiobook' %>
          <%= f.label :type_audiobook, 'Audiobook'%>
        </div>
        <br>
        <div>
          <%=f.label :language, 'Language'%>
          <%=f.select :language, {'Русский' => :ru, 'English' => :en}, selected: :ru%>
        </div>
        <br>
        <div>
          <%=f.label :poster, style: (@book.errors[:poster].any? ? 'color: red;' : '')%>
          <%=f.file_field :poster%>
          <%=f.label :background_image%>
          <%=f.file_field :background_image%>
        </div>
        <div>
          <%=f.label :publish_at%>
          <%=f.text_field :published_at, type: 'date'%>
        </div>
        <div>
          Publishing house
          <%=f.select :publishing_house_id, @publishing_houses.collect {|ph| ["#{ph.name} (#{ph.id})", ph.id] }%>
          <%=link_to 'Add one', new_publishing_house_path, target: '_blank'%>
          <hr>
        </div>

        <div style="background-color: #b7e4e1;
            box-shadow: 0 0 10px 1px black;
            padding: 10px;">
          <h4 style="margin-top: 0;">Если такая книга уже есть, впишите в это поле её id, и проигнорируйте остальные данные;<br>
            иначе оставьте это поле пустым (если в поле есть данные, приоритет отдаётся ему)</h4>
          <div style="color: red;"><%=flash[:author_ids_errors]%></div>
          <input name="same_book_id" type="text" placeholder="id книги" value="<%=params[:same_book_id]%>">

          <hr>
          <br><br>

          <div style="color: red;"><%=flash[:abstract_book_errors]%></div>
          <input name="author_ids" type="text" placeholder="id авторов через запятую" value="<%=params[:author_ids]%>">
          <%=link_to 'Add author', new_author_path, target: '_blank'%>
          <br>
          <input name="abstract_book[original_name]" type="text" placeholder="Название оригинальной книги" value="<%=@abstract_book.original_name%>">
          <br>
          <label for="abstract_book[published_at]">Дата выпуска оригинальной книги</label>
          <input id="abstract_book[published_at]" name="abstract_book[published_at]" type="date" value="<%=@abstract_book.published_at%>">
        </div>
        <hr>
        <br>
        <%=f.submit 'Add', name: nil%>
    <%end%>
  </div>



  <div class="top-block-main-column">
    <div class="panel-edit-book">
      <div class="fields-for-filling">
        <textarea placeholder="Описание" name="comment" cols="40" rows="3" class="description-field"></textarea>

        <div class="area-for-filling">
          <label for="book_language">Language </label>
          <select name="book[language]" id="book_language">
            <option selected="selected" value="ru">Русский</option>
            <option value="en">English</option>
          </select>
        </div>

        <div class="area-for-filling">
          <label for="book_publish_at">Publish at </label>
          <input type="date" name="book[published_at]" id="book_published_at">
        </div>
        <div class="area-for-filling">
          <label>Publishing house </label>
          <select name="book[publishing_house_id]" id="book_publishing_house_id"><option value="19">Эксмо (19)</option>
            <option value="18">G-Unit Books (18)</option>
            <option value="17">SAGE Publications (17)</option>
            <option value="16">Manning Publications (16)</option>
            <option value="15">Lion Hudson (15)</option>
            <option value="14">Broadview Press (14)</option>
            <option value="13">Brimstone Press (13)</option>
            <option value="12">Gefen Publishing House (12)</option>
            <option value="11">Unfinished Monument Press (11)</option>
            <option value="10">Tate Publishing &amp; Enterprises (10)</option>
            <option value="9">Central European University Press (9)</option>
            <option value="8">Barrie &amp; Jenkins (8)</option>
            <option value="7">Allen Ltd (7)</option>
            <option value="6">Heyday Books (6)</option>
            <option value="5">Borgo Press (5)</option>
            <option value="4">Virgin Publishing (4)</option>
            <option value="3">Etruscan Press (3)</option>
            <option value="2">Zondervan (2)</option>
            <option value="1">No Starch Press (1)</option></select>
          <a target="_blank" href="/publishing_houses/new" class="button-add-publ">Add one</a>
        </div>

      </div>
      <div class="block-character">

        <div class="block-evaluation">
          <div class="add-book"><div>ДОБАВИТЬ</div></div>
          <div class="add-book"><div>УДАЛИТЬ</div></div>
        </div>
      </div>
    </div>
    <div class="block-related-books">
      <div class="category-book">
        <div class="ebook-block active">
          <div class="img-ebook-block"></div>
          <div class="text-ebook-block">Цифровые книги</div>
        </div>
        <div class="aubook-block">
          <div class="img-aubook-block"></div>
          <div class="text-aubook-block">Цифровые аудиокниги</div>
        </div>
        <div class="pbook-block">
          <div class="img-pbook-block"></div>
          <div class="text-pbook-block">Печатные книги</div>
        </div>
      </div>
      <div class="cont-category-book">

        <div class="tab-category">
          <div id="add-book-related" class="stand-round-button"><div></div></div>
          <div class="absent">Книги отсутствуют</div>
        </div>
        <div class="tab-category">
          <div id="add-book-related" class="stand-round-button"><div></div></div>
          <div class="absent">Аудиокниги отсутствуют</div>
        </div>
        <div class="tab-category">
          <div id="add-book-related" class="stand-round-button"><div></div></div>
          <div class="absent">Печатные книги отсутствуют</div>

        </div>

      </div>
    </div>
  </div>
</div>
<%
  # add new book
  #b=Book.new(abstract_book: AbstractBook.first, publishing_house: PublishingHouse.first)
%>