config/routes.rb
p 'routes is initializing'

Rails.application.routes.draw do
  root 'home#index'
  match 'console' => 'home#console', via: :all

  # SessionsController
  match '/login(?redirect_to=:redirect_page)', to: 'sessions#new', via: :get, as: :signin
  match '/login', to: 'sessions#create', via: :post
  match '/signout(?redirect_to=:redirect_page)', to: 'sessions#destroy', via: :delete, as: :signout
  get '/users/find'


  # UsersController
  match '/register(?redirect_to=:redirect_page)', to: 'users#new', via: :get, as: :signup
  match '/register', to: 'users#create', via: :post
  match '/users', to: 'users#index', via: :get
  match '/settings', to: 'users#edit_current_user', via: :get, as: :current_user_settings # only singed in
  match '/settings', to: 'users#update_current_user', via: :patch # only singed in
  resources :users, only: [:edit, :show] # only admin


  resources :books
  match 'books/new' => 'books#create', via: :post


  resources :authors
  match 'authors/new' => 'authors#create', via: :post


  resources :publishing_houses
  match 'publishing_houses/new' => 'publishing_houses#create', via: :post
end

app/views/layouts/application.html.erb
<%#console if Rails.env.development?%>
<%#console if Rails.env.production?%>
<%
@redirect_path = request.path
@redirect_path = nil if @redirect_path == '/'
%>
<!DOCTYPE html>
<html ng-app="main">
<head>
    <title>BookLife</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.5/angular.min.js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/showdownjs/showdown/1.7.2/dist/showdown.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css">
  .field_with_errors > *{
  border-color: red;
}
</style>
  </head>

<body>

  <div style="text-align: right; position: absolute; top: 0; right: 0;">
    <%=link_to 'Books', books_path%>
    <%=link_to 'Main', root_path%>
    <%=link_to 'Register', signup_path%>
    <%=link_to 'Login', signin_path(@redirect_path)%>
    <%=link_to 'Signout', signout_path(@redirect_path), method: :delete%>
    <%=link_to 'Settings', current_user_settings_path%>
  </div>
  <div class="background-subscription">
    <!--authform.(coffee|scss)-->
    <%unless signed_in?%>
      <%=form_for User.new, url: signup_path, html: {class: 'for-the-subscription-window'}, authenticity_token: false do |f|%>
          <%=hidden_field_tag 'authenticity_token', form_authenticity_token%>
          <h1>Вход или регистрация</h1>
          <div id="answer"></div>
          <div class="credential-mail">
            <img id="user_icon_form" class="user-icon" />
            <%=f.text_field :email, type: :email, class: 'field-for-entering-personal-data email', placeholder: 'Ваша почта' %>
          </div>
          <%=f.password_field :password, class: 'field-for-entering-personal-data', placeholder: 'Пароль' %>
          <div id="registration_fields" class="registration-fields" data-action="sign_in">
            <div class="fields-for-name">
              <%=f.text_field :first_name, class: 'field-for-entering-personal-data', placeholder: 'Ваше имя', style: 'margin-right: 10px;' %>
              <%=f.text_field :surname, class: 'field-for-entering-personal-data', placeholder: 'Ваша фамилия' %>
            </div>
            <!--<input type="text" name="learned" id="learned" class="field-for-entering-personal-data" placeholder="[Откуда Вы о нас узнали?]">-->
          </div>
          <input type="submit" id="signing" class="button-to-send" data-sign-in="Вход" data-sign-up="Регистрация" value="Регистрация">
      <%end%>
    <%end%>
    <!--<form action="" id="feedback" name="subscription" method="post" class="for-the-subscription-window">-->
      <!--<h1>Вход или регистрация</h1>-->
      <!--<div id="answer"></div>-->
      <!--<div class="credential-mail">-->
        <!--<img src="/images/user.jpg" />-->
        <!--<input type="text" name="email" id="email" class="field-for-entering-personal-data" required="" placeholder="Ваша почта">-->
      <!--</div>-->
      <!--<div class="fields-for-name">-->
        <!--<input type="text" name="name" id="name" style="margin-right: 10px;" class="field-for-entering-personal-data" required="" placeholder="Ваше имя">-->
        <!--<input type="text" name="surname" id="surname" class="field-for-entering-personal-data" required="" placeholder="Ваше фамилия">-->
      <!--</div>-->
      <!--<input type="text" name="learned" id="learned" class="field-for-entering-personal-data" required="" placeholder="Откуда Вы о нас узнали?">-->
      <!--<input type="text" name="password" id="password" class="field-for-entering-personal-data" required="" placeholder="Пароль">-->
      <!--&lt;!&ndash;<input type="submit" name="ok" value="Отправить" class="">&ndash;&gt;-->
      <!--<button class="button-to-send" name="login">Вход</button>-->
      <!--<button class="button-to-send" name="registration">Регистрация</button>-->
      <!--<p>Регистрируясь, я принимаю <a href="/">условия использования</a></p>-->
    <!--</form>-->
    <div class="closed-background-subscription"></div>
  </div>




  <header>
    <a href="/" class="logo"></a>

    <div class="search"><input type="text" value="" placeholder="Книга, автор, жанр и цитата"></div>

    <ul class="under-the-menu">
      <li><a href="#">Главная</a></li>
      <li><a href="#">Рекомендуем</a></li>
      <li><a href="#">Книги</a></li>
    </ul>

  </header>
  <div class="left-menu">
    <a href="#" role="button" class="btm-menu btm-open-menu"><div class="icon-menu icon-open-menu"></div></a>
    <a href="/" role="button" class="btm-menu"><div class="icon-menu icon-news"></div></a>
    <a href="/books" role="button" class="btm-menu active-btm-menu"><div class="icon-menu icon-lib"></div></a>
    <%if signed_in?%>
          <%=link_to settings_path, class: 'btm-menu' do%>
              <div class="icon-menu icon-account"></div>
          <%end%>
    <%end%>
    <%=link_to users_path, class: 'btm-menu' do%>
        <div class="icon-menu icon-people"></div>
    <%end%>
    <a href="#" role="button" class="btm-menu"><div class="icon-menu icon-community"></div></a>
    <a href="#" role="button" class="btm-menu"><div class="icon-menu icon-still"></div></a>

    <a href="#" class="poster-last-book"><img src="/images/ico/book.jpg" /></a>




    <% if signed_in? %>
        <div class="user-left-menu">
          <img src="<%=current_user.thumbnail%>" />
          <div class="alerts-left-menu">0</div>
        </div>
    <%else%>
        <div id="open_auth_form" class="login-mini login"><div class="icon-login"><div></div></div></div>
    <% end %>

  </div>


  <div class="pop-up-menu">
    <div class="background-menu"></div>

    <div class="panel-menu">
      <div class="header-panel-menu">
        <div role="button" class="btm-menu btm-open-menu"><div class="icon-menu icon-open-menu"></div></div>
        <a href="/" class="logo-pop-up-menu"></a>
      </div>
      <div class="search"><input type="text" value="" placeholder="Книга, автор, жанр и цитата"></div>

      <div class="btms-panel-menu">
        <a href="#" role="button" class="btm-panel-menu"><div class="carcass-panel-menu"><div class="icon-menu icon-news"></div></div><div class="text-btm-panel-menu">Лента</div></a>
        <a href="/books" role="button" class="btm-panel-menu"><div class="carcass-panel-menu"><div class="icon-menu icon-lib"></div></div><div class="text-btm-panel-menu">Библиотека</div></a>
        <%if signed_in?%>
              <%=link_to settings_path, class: 'btm-panel-menu' do%>
                  <div class="carcass-panel-menu"><div class="icon-menu icon-account"></div></div><div class="text-btm-panel-menu">Профиль</div>
              <%end%>
        <%end%>
        <%=link_to users_path, class: 'btm-panel-menu' do%>
            <div class="carcass-panel-menu"><div class="icon-menu icon-people"></div></div><div class="text-btm-panel-menu">Люди</div>
        <%end%>
        <a href="#" role="button" class="btm-panel-menu"><div class="carcass-panel-menu"><div class="icon-menu icon-community"></div></div><div class="text-btm-panel-menu">Сообщества</div></a>
      </div>

      <div class="head-continue">
        <img class="img-head-continue" src="/images/ico/book.jpg">
        <span class="text-head-continue">Продолжить...</span>

        <div class="head-reveal-history-of-reading"><div></div></div>
      </div>



      <% if signed_in? %>
          <div class="head-user-panel">
            <img class="img-head-user-panel" src="<%=current_user.thumbnail%>">

            <div class="text-head-user-panel">
              <div class="name-head-user-panel"><%=user_full_name current_user%></div>
              <a href="/" class="subscription-head-user-panel"><div></div>Без подписки</a>
            </div>

            <div class="notification-head-user-panel"><div class="icon-notification"></div><div class="alerts-left-menu">0</div></div>
            <div class="bottom-arrow-head-user-panel"><div></div></div>

          </div>
      <%else%>
          <div id="open_auth_form" class="login-pop-up-menu login"><div class="btm-login">ВХОД ИЛИ РЕГИСТРАЦИЯ</div></div>
      <% end %>
    </div>
  </div>



  <!-- Левое поле -->
  <!--<? if($path == 'book.php' || $path == 'reviews.php' || $path == 'user.php') : ?>-->
  <%= render 'shared/left_menu' if (params[:controller] == 'users' and params[:action] == 'show') or (params[:controller] == 'books' and params[:action] == 'show') or (params[:controller] == 'books' and params[:action] == 'new')%>
  <!--<? endif; ?>-->
  <div class="main-column-catalog">
    <!-- require 'views/' . $path; -->
    <%if flash[:notice]%>
      <h2 style="background-color: #d0d0d0"><%=flash[:notice]%></h2>
    <%end%>
    <%=yield%>
  </div>
<!--
<%=request.host%>
<%=request.domain%>
<% for i in 0..10%>
  <%=request.domain(i)%>
<%end%>


-->
</body>
</html>